name: Build and Deploy Angular Projects

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: 1. Checkout Repo
      uses: actions/checkout@v4

    - name: 2. Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 3. Build Angular Projects
      run: |
        cd arroyo-johnmatthew/one_piece
        npm install
        npm run build -- --base-href /exercise-6-appvengers/one_piece/ --configuration production
        cd ../..
        
        cd delima-justine/marvel
        npm install
        npm run build -- --base-href /exercise-6-appvengers/marvel/ --configuration production
        cd ../..
        
        cd mejares-jamesmichael/kamen-rider
        npm install
        npm run build -- --base-href /exercise-6-appvengers/kamen-rider/ --configuration production
        cd ../..
        
        cd ynion-mabeamae/drama
        npm install
        npm run build -- --base-href /exercise-6-appvengers/drama/ --configuration production
        cd ../..

    - name: 4. Prepare Deploy Directory
      run: |
        mkdir deploy
        cp -r arroyo-johnmatthew/one_piece/dist/one_piece/browser/ deploy/one_piece
        cp -r delima-justine/marvel/dist/marvel/browser/ deploy/marvel
        cp -r mejares-jamesmichael/kamen-rider/dist/kamen-rider/browser/ deploy/kamen-rider
        cp -r ynion-mabeamae/drama/dist/drama/browser/ deploy/drama
        echo '<html><head><title>Project Hub</title></head><body><h1>Our Angular Projects</h1><ul><li><a href="one_piece">One Piece</a></li><li><a href="marvel">Marvel</a></li><li><a href="kamen-rider">Kamen Rider</a></li><li><a href="drama">Drama</a></li></ul></body></html>' > deploy/index.html

    - name: 5. Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: deploy
        clean: true